import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RoVSRG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-full">
        <div className="bg-in-game h-full w-full blur-sm rounded-md absolute"/>
        <h1 className="text-white text-6xl font-bold grid place-items-center h-screen">RoBeats fork focused on skill.</h1>
      </main>
    </div>
  )
}
 