import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Game from "./components/home/game"

export default function Home() {
  return (
    <div className="flex flex-col">
      <Head>
        <title>RoVSRG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1 className="font-bold mb-[5rem] mt-10 text-center text-6xl">Thinking differently about rhythm games.</h1>

      <div className="text-center mb-[6rem]">
        <h1 className="text-xl font-bold mb-5">Our Games</h1>

        <div className="flex flex-row justify-center gap-5">
          <Game universeId={1643537246} src="/thumbs/robeatscs.png">RoBeats CS</Game>
          <Game universeId={1647009366} src="/thumbs/rosu.png">rosu!</Game>
        </div>
      </div>

      <main className="w-full h-full bg-in-game rounded-l">
        <h1 className="text-white text-6xl font-bold grid place-items-center h-screen">RoBeats fork focused on skill.</h1>
      </main>
    </div>
  )
}
 